name: Spellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # manual run

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.34.0
        with:
          config_path: .spellcheck.yml
